name: Calling
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "coder9A"
        required: false

jobs:
  calling-a-reusable-wf:
    uses: ./.github/workflows/reusable-workflow.yaml
  using-reusable-wf-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-wf
    steps:
      - run: echo ${{ needs.calling-a-reusable-wf.outputs.date }}



